title: Media & Society 
description: A pocket textbook for Media & Society
theme: just-the-docs

url: https://marionwalton.github.io/media-and-society/
heading_anchors: true
favicon_ico: "/img/avatar.ico"
footer_content: "Media and Society - A Pocket Textbook Â© 2026 by Marion Walton, Adam Haupt, Wallace Chuma, Martha Evans & Danielle Becker is licensed under Creative Commons Attribution-ShareAlike 4.0 International. Cite as: Walton, M., et al. 2026. Media & Society: A Pocket Textbook. Available https://marionwalton.github.io/media-and-society/" 
callouts:
  warning:
    title: Warning
    color: red
  activity:
    title: Activity
    color: yellow
  question:
    title: Question
    color: green
  survey:
    title: What do you think?
    color: purple
  example:
    title: Example
    color: yellow
  definition:
    title: Definition
    color: blue